# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dccl_acoustic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x63\x63l_acoustic.proto\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\xf1\x01\n\x0f\x42\x65\x61\x63onTelemetry\x12$\n\x03lat\x18\x01 \x01(\x01\x42\x17\xa2?\x14 \x07)\x00\x00\x00\x00\x00\x80V\xc0\x31\x00\x00\x00\x00\x00\x80V@\x12$\n\x03lon\x18\x02 \x01(\x01\x42\x17\xa2?\x14 \x07)\x00\x00\x00\x00\x00\x80\x66\xc0\x31\x00\x00\x00\x00\x00\x80\x66@\x12&\n\x05\x64\x65pth\x18\x03 \x01(\x01\x42\x17\xa2?\x14 \x02)\x00\x00\x00\x00\x00\x00\x00\x00\x31\x00\x00\x00\x00\x00p\xa7@\x12$\n\x03svs\x18\x04 \x01(\x01\x42\x17\xa2?\x14 \x01)\x00\x00\x00\x00\x00P\x94@1\x00\x00\x00\x00\x00\x90\x9a@\x12&\n\x05speed\x18\x05 \x01(\x01\x42\x17\xa2?\x14 \x02)\x00\x00\x00\x00\x00\x00\x00\x00\x31\x00\x00\x00\x00\x00\x00$@\x12\x11\n\x02\x62t\x18\x06 \x01(\tB\x05\xa2?\x02H\x10:\t\xa2?\x06\x08|\x10 (\x04\"\x85\x01\n\x04Pose\x12$\n\x03lat\x18\x01 \x02(\x01\x42\x17\xa2?\x14 \x07)\x00\x00\x00\x00\x00\x80V\xc0\x31\x00\x00\x00\x00\x00\x80V@\x12$\n\x03lon\x18\x02 \x02(\x01\x42\x17\xa2?\x14 \x07)\x00\x00\x00\x00\x00\x80\x66\xc0\x31\x00\x00\x00\x00\x00\x80\x66@\x12&\n\x05\x64\x65pth\x18\x03 \x01(\x01\x42\x17\xa2?\x14 \x02)\x00\x00\x00\x00\x00\x00\x00\x00\x31\x00\x00\x00\x00\x00p\xa7@:\t\xa2?\x06\x08}\x10\x10(\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dccl_acoustic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['lat']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['lat']._serialized_options = b'\242?\024 \007)\000\000\000\000\000\200V\3001\000\000\000\000\000\200V@'
  _globals['_BEACONTELEMETRY'].fields_by_name['lon']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['lon']._serialized_options = b'\242?\024 \007)\000\000\000\000\000\200f\3001\000\000\000\000\000\200f@'
  _globals['_BEACONTELEMETRY'].fields_by_name['depth']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['depth']._serialized_options = b'\242?\024 \002)\000\000\000\000\000\000\000\0001\000\000\000\000\000p\247@'
  _globals['_BEACONTELEMETRY'].fields_by_name['svs']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['svs']._serialized_options = b'\242?\024 \001)\000\000\000\000\000P\224@1\000\000\000\000\000\220\232@'
  _globals['_BEACONTELEMETRY'].fields_by_name['speed']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['speed']._serialized_options = b'\242?\024 \002)\000\000\000\000\000\000\000\0001\000\000\000\000\000\000$@'
  _globals['_BEACONTELEMETRY'].fields_by_name['bt']._options = None
  _globals['_BEACONTELEMETRY'].fields_by_name['bt']._serialized_options = b'\242?\002H\020'
  _globals['_BEACONTELEMETRY']._options = None
  _globals['_BEACONTELEMETRY']._serialized_options = b'\242?\006\010|\020 (\004'
  _globals['_POSE'].fields_by_name['lat']._options = None
  _globals['_POSE'].fields_by_name['lat']._serialized_options = b'\242?\024 \007)\000\000\000\000\000\200V\3001\000\000\000\000\000\200V@'
  _globals['_POSE'].fields_by_name['lon']._options = None
  _globals['_POSE'].fields_by_name['lon']._serialized_options = b'\242?\024 \007)\000\000\000\000\000\200f\3001\000\000\000\000\000\200f@'
  _globals['_POSE'].fields_by_name['depth']._options = None
  _globals['_POSE'].fields_by_name['depth']._serialized_options = b'\242?\024 \002)\000\000\000\000\000\000\000\0001\000\000\000\000\000p\247@'
  _globals['_POSE']._options = None
  _globals['_POSE']._serialized_options = b'\242?\006\010}\020\020(\004'
  _globals['_BEACONTELEMETRY']._serialized_start=54
  _globals['_BEACONTELEMETRY']._serialized_end=295
  _globals['_POSE']._serialized_start=298
  _globals['_POSE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
