serial:
  port: "/dev/ttyUSB0"
  port_fallback: "/dev/ttyUSB4"
  baudrate: 9600
  leader1: "$P001"
  leader2: "$P002"
  sound_velocity: 1500
  timeout_threshold: 0.5

leader_gps_topic: "/leader1/code/gps"
leader_gps_msg_type: "NavSatFix"  # or "GeoPoint"